name: Publish Package to npmjs

on:
  release:
    types:
      - published

jobs:

  npm-publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # https://nodejs.org/en/about/releases/
        registry-url: 'https://registry.npmjs.org'

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
